name: modular_example
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_modular: ^3.0.0-nullsafety.29
  flutter_mobx: ^2.0.0-nullsafety.0
  mobx: ^2.0.0-nullsafety.2
  dartz: ^0.10.0-nullsafety.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  # build_runner: ^1.10.12
  # mobx_codegen: ^1.1.2

flutter:
  uses-material-design: true
